apiVersion: v1
kind: Service
metadata:
  name: home-brain-backend
  namespace: default
spec:
  selector:
    app: home-brain-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP