# argo-values.yaml

# 1. Force Global Components to Master
global:
  nodeSelector:
    kubernetes.io/hostname: k3s-master

# 2. Specific Component Overrides (Just to be safe)
controller:
  nodeSelector:
    kubernetes.io/hostname: k3s-master
repoServer:
  nodeSelector:
    kubernetes.io/hostname: k3s-master
server:
  nodeSelector:
    kubernetes.io/hostname: k3s-master
redis:
  nodeSelector:
    kubernetes.io/hostname: k3s-master

# 3. Disable HA (High Availability) for Home Lab
redis-ha:
  enabled: false