apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-scraper
  namespace: web-scraper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-scraper-job-manager
  namespace: web-scraper
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  # Tailscale permissions
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update", "create"]
    resourceNames: ["tailscale"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-scraper-job-manager
  namespace: web-scraper
subjects:
  - kind: ServiceAccount
    name: web-scraper
    namespace: web-scraper
roleRef:
  kind: Role
  name: web-scraper-job-manager
  apiGroup: rbac.authorization.k8s.io
