apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
  namespace: immich
type: Opaque
stringData:
  DB_PASSWORD: "changeThisPassword123"  # TODO: Change this!
  JWT_SECRET: "changeThisSecretKey456"  # TODO: Change this!
