apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      serviceAccountName: immich
      containers:
      - name: immich-server
        image: ghcr.io/immich-app/immich-server:release
        ports:
        - containerPort: 2283
        env:
        - name: IMMICH_MACHINE_LEARNING_ENABLED
          value: "true"
        - name: IMMICH_PORT
          value: "2283"
        envFrom:
        - configMapRef:
            name: immich-config
        - secretRef:
            name: immich-secrets
        volumeMounts:
        - name: library
          mountPath: /usr/src/app/upload
        - name: camera-uploads
          mountPath: /CameraUploads
          readOnly: true
        - name: jongdee-drive
          mountPath: /JongdeeDrive
          readOnly: true
        - name: por-drive
          mountPath: /PorDrive
          readOnly: true
        - name: poon-drive
          mountPath: /PoonDrive
          readOnly: true
        - name: churin-drive
          mountPath: /ChurinDrive
          readOnly: true
        - name: orawan-drive
          mountPath: /OrawanDrive
          readOnly: true
        - name: ipcamera
          mountPath: /IPCcamera
          readOnly: true
        - name: kanokgan-drive
          mountPath: /KanokganDrive
          readOnly: true
        - name: nrop
          mountPath: /Nrop
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      volumes:
      - name: library
        persistentVolumeClaim:
          claimName: immich-library-pvc
      - name: camera-uploads
        hostPath:
          path: /mnt/CameraUploads
          type: Directory
      - name: jongdee-drive
        hostPath:
          path: /mnt/JongdeeDrive
          type: Directory
      - name: por-drive
        hostPath:
          path: /mnt/PorDrive
          type: Directory
      - name: poon-drive
        hostPath:
          path: /mnt/PoonDrive
          type: Directory
      - name: churin-drive
        hostPath:
          path: /mnt/ChurinDrive
          type: Directory
      - name: orawan-drive
        hostPath:
          path: /mnt/OrawanDrive
          type: Directory
      - name: ipcamera
        hostPath:
          path: /mnt/IPCamera
          type: Directory
      - name: kanokgan-drive
        hostPath:
          path: /mnt/KanokganDrive
          type: Directory
      - name: nrop
        hostPath:
          path: /mnt/Nrop
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  selector:
    app: immich-server
  ports:
  - port: 80
    targetPort: 2283
